#!/usr/bin/env python3
"""
check_program_ids.py — Hard-gate against Anchor.toml ↔ declare_id ↔ deployments drift.

Runs in CI and locally.  Fails fast when the program IDs declared in
`Anchor.toml` (the source of truth consumed by the circuits, the TS SDK, and
`declare_id!` macros in the on-chain programs) diverge from:

  (1) the `declare_id!(...)` literal in each program's `src/lib.rs`;
  (2) the `SCHEMA_REGISTRY_PROGRAM_ID` and `ISSUER_REGISTRY_PROGRAM_ID`
      literals in `crates/solid-light/src/cpi_helpers.rs`
      (SOLID-SEC-032 / ADR-0014);
  (3) the program IDs recorded in `deployments/<cluster>.json`;
  (4) the presence of a `deployments/<cluster>.json` for every non-localnet
      cluster declared in Anchor.toml (SOLID-SEC-040, Phase 2 prelude).

Exit code 0: everything consistent.
Exit code 1: drift detected — prints an actionable diff.
Exit code 2: structural problem (missing file, malformed manifest).
"""

from __future__ import annotations
import json
import os
import pathlib
import re
import sys
from typing import Dict, Tuple

# Repo root: defaults to two levels up from this file, but can be
# overridden via $SOLID_REPO_ROOT for tests.  The override IS the
# testability hook -- without it, regression tests for SOLID-SEC-081
# would have to create files inside the live tree (fragile if the
# test crashes; bad signal if a stale sentinel files lingers).
ROOT = pathlib.Path(
    os.environ.get(
        "SOLID_REPO_ROOT",
        str(pathlib.Path(__file__).resolve().parent.parent),
    )
)
ANCHOR_TOML = ROOT / "Anchor.toml"
DEPLOYMENTS_DIR = ROOT / "deployments"

# Maps the toml section name (anchor) ↔ the JSON key (deployments/*.json).
PROGRAM_KEYS: Tuple[str, ...] = ("zk_verifier", "issuer_registry", "schema_registry")

# Files under programs/*/src/lib.rs that must carry a matching declare_id!().
DECLARE_ID_PATHS: Dict[str, pathlib.Path] = {
    "zk_verifier":     ROOT / "programs/zk-verifier/src/lib.rs",
    "issuer_registry": ROOT / "programs/issuer-registry/src/lib.rs",
    "schema_registry": ROOT / "programs/schema-registry/src/lib.rs",
}

# SOLID-SEC-032: the zk-verifier program owner-checks tree PDAs against a
# hardcoded SCHEMA_REGISTRY_ID_BYTES constant in solid-light/src/cpi_helpers.rs.
# A drift between that constant and the schema_registry program ID in
# Anchor.toml silently re-opens the forged-trust-root attack (ADR-0010).
# We validate the base58 string literal here. The companion Rust tests in
# `crates/solid-light/src/cpi_helpers.rs` (id_bytes_tests) validate the
# byte array against the string.
CPI_HELPERS_PATH: pathlib.Path = ROOT / "crates/solid-light/src/cpi_helpers.rs"

# SOLID-SEC-081 (NF-05): TypeScript files that carry the canonical program
# IDs as literal strings.  Each entry maps a file path (repo-relative) to
# the set of programs it is allowed to name.  Every other .ts file under
# the scanned directories MUST NOT name any of these IDs as a literal --
# they should import from `@solid-protocol/core`'s `PROGRAM_PUBKEYS`.
#
# Drift surface (pre-fix): a typo in any of these four files would break
# the on-chain owner-check on issue/verify but compile cleanly.  CI's
# program-ID gate validated only Rust + JSON; TS literals were silent.
TS_PROGRAM_ID_OWNERS: Dict[str, Tuple[str, ...]] = {
    "ts-sdk/packages/core/src/index.ts": ("zk_verifier", "issuer_registry", "schema_registry"),
    "ts-sdk/packages/sdk/src/config.ts": ("zk_verifier", "issuer_registry", "schema_registry"),
    "ts-sdk/packages/light/src/index.ts": ("issuer_registry", "schema_registry"),
    "tests/integration/01_registry_init.test.ts": ("issuer_registry",),
}

# Directories to walk for the unauthorized-literal scan.  Only `src/` of
# each ts-sdk package is checked -- `dist/` is regenerated by tsc and
# would always echo the (correct or drifted) source values.  scripts/
# is included because anyone could regress by hard-coding an ID inside a
# bootstrap script; the canonical pattern is to import from
# `@solid-protocol/core`.  tests/integration/ is included with the one
# allowlisted test acting as the only legitimate consumer.
TS_SCAN_DIRS: Tuple[pathlib.Path, ...] = (
    ROOT / "ts-sdk" / "packages" / "core" / "src",
    ROOT / "ts-sdk" / "packages" / "issuer" / "src",
    ROOT / "ts-sdk" / "packages" / "holder" / "src",
    ROOT / "ts-sdk" / "packages" / "verifier" / "src",
    ROOT / "ts-sdk" / "packages" / "light" / "src",
    ROOT / "ts-sdk" / "packages" / "sdk" / "src",
    ROOT / "scripts",
    ROOT / "tests" / "integration",
)


def read_anchor_toml() -> Dict[str, Dict[str, str]]:
    """Return {cluster: {program_name: pubkey}} from `[programs.<cluster>]`."""
    text = ANCHOR_TOML.read_text()
    out: Dict[str, Dict[str, str]] = {}
    cur_cluster: str | None = None
    for line in text.splitlines():
        s = line.strip()
        m = re.match(r"\[programs\.([A-Za-z0-9_]+)\]", s)
        if m:
            cur_cluster = m.group(1)
            out.setdefault(cur_cluster, {})
            continue
        if s.startswith("["):
            cur_cluster = None
            continue
        if cur_cluster is None:
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*"([^"]+)"', s)
        if m:
            out[cur_cluster][m.group(1)] = m.group(2)
    return out


def read_declare_ids() -> Dict[str, str]:
    """Parse the `declare_id!("…")` literal from each program's lib.rs."""
    out: Dict[str, str] = {}
    for name, path in DECLARE_ID_PATHS.items():
        if not path.exists():
            sys.exit(f"[fatal] missing program source: {path}")
        for line in path.read_text().splitlines():
            m = re.match(r'\s*declare_id!\("([^"]+)"\)\s*;', line)
            if m:
                out[name] = m.group(1)
                break
        else:
            sys.exit(f"[fatal] no declare_id! in {path}")
    return out


def read_cpi_helpers_literal(const_name: str) -> str | None:
    """Return the base58 literal assigned to `const_name` in cpi_helpers.rs.

    `None` if the file is missing; empty string if the constant is not
    present in a recognized form (caller treats either as a failure).
    """
    if not CPI_HELPERS_PATH.exists():
        return None
    text = CPI_HELPERS_PATH.read_text()
    m = re.search(
        rf'pub\s+const\s+{re.escape(const_name)}\s*:\s*&str\s*=\s*"([^"]+)"\s*;',
        text,
    )
    return m.group(1) if m else ""


def read_cpi_helpers_schema_registry_literal() -> str | None:
    """Back-compat wrapper -- kept so callers don't have to spell the
    constant name each time."""
    return read_cpi_helpers_literal("SCHEMA_REGISTRY_PROGRAM_ID")


# Solana base58 alphabet (no `0`, `O`, `I`, `l`).  Pubkeys are 32 bytes
# encoded base58 -> 43 or 44 chars.  We're conservative and accept 32-44
# to avoid a future change in encoding length missing a literal.
_BASE58_PUBKEY = re.compile(
    r"['\"]([1-9A-HJ-NP-Za-km-z]{32,44})['\"]"
)


def scan_ts_files_for_pubkey_literals(
    canonical_ids: Dict[str, str],
) -> Tuple[Dict[str, Dict[str, str]], list[str]]:
    """Walk `TS_SCAN_DIRS` and return (owners_seen, violations).

    `owners_seen[file] = {program: id_literal}` for every allowlisted
    file that actually contains a canonical pubkey -- caller verifies
    each `id_literal` against `canonical_ids[program]`.

    `violations` is a list of human-readable error messages: each non-
    allowlisted .ts file that contains a canonical pubkey literal, or
    each allowlisted file whose literal does not match the canonical.

    SOLID-SEC-081 (NF-05): closing this gate stops a typo in any TS
    program-ID literal from silently breaking the on-chain owner-check
    on issue / verify.  The Rust side has had this gate since
    SOLID-SEC-032; this brings the TS side to parity.
    """
    canonical_to_program: Dict[str, str] = {
        pid: program for program, pid in canonical_ids.items()
    }
    owners_seen: Dict[str, Dict[str, str]] = {}
    violations: list[str] = []

    for scan_dir in TS_SCAN_DIRS:
        if not scan_dir.is_dir():
            continue
        for ts_file in sorted(scan_dir.rglob("*.ts")):
            # Skip .d.ts (type-declaration) files; they echo the source.
            if ts_file.suffix == ".ts" and ts_file.stem.endswith(".d"):
                continue
            rel = ts_file.relative_to(ROOT).as_posix()
            text = ts_file.read_text()
            for match in _BASE58_PUBKEY.findall(text):
                if match not in canonical_to_program:
                    # Some other base58 string (e.g. SPL AC program ID,
                    # SPL Noop program ID, etc.).  Not in scope for this
                    # gate; the Rust side has separate constants for
                    # those.
                    continue
                program = canonical_to_program[match]
                if rel in TS_PROGRAM_ID_OWNERS:
                    if program not in TS_PROGRAM_ID_OWNERS[rel]:
                        violations.append(
                            f"{rel} contains canonical `{program}` ID "
                            f"({match}) but its allowlist entry only "
                            f"permits {sorted(TS_PROGRAM_ID_OWNERS[rel])}"
                        )
                    else:
                        owners_seen.setdefault(rel, {})[program] = match
                else:
                    violations.append(
                        f"{rel} hard-codes canonical `{program}` program "
                        f"ID ({match}) but is NOT in the SOLID-SEC-081 "
                        f"allowlist.  TS files that need a program ID "
                        f"should `import {{ PROGRAM_PUBKEYS }} from "
                        f"'@solid-protocol/core'` or add an explicit "
                        f"entry in `scripts/check_program_ids.py::"
                        f"TS_PROGRAM_ID_OWNERS`."
                    )

    return owners_seen, violations


def read_deployments() -> Dict[str, Dict[str, str]]:
    """Return {cluster: {program_name: pubkey}} from deployments/*.json."""
    out: Dict[str, Dict[str, str]] = {}
    if not DEPLOYMENTS_DIR.is_dir():
        return out
    for path in sorted(DEPLOYMENTS_DIR.glob("*.json")):
        try:
            obj = json.loads(path.read_text())
        except Exception as exc:
            sys.exit(f"[fatal] {path}: invalid JSON: {exc}")
        cluster = obj.get("network") or path.stem
        progs = obj.get("programs", {}) or {}
        out[cluster] = {name: meta["program_id"] for name, meta in progs.items()}
    return out


def main() -> int:
    failures: list[str] = []

    anchor = read_anchor_toml()
    declared = read_declare_ids()
    deployments = read_deployments()

    # (1) declare_id!() must match Anchor.toml — for every cluster the ID has
    #     to be the same across clusters (it IS the same program binary).
    #     If Anchor.toml lists different IDs per cluster, we require declare_id
    #     to match ONE of them and all others to match the same.
    if not anchor:
        failures.append("Anchor.toml has no [programs.<cluster>] sections")
    else:
        for program in PROGRAM_KEYS:
            seen: set[str] = set()
            for cluster, prog_map in anchor.items():
                if program not in prog_map:
                    failures.append(f"Anchor.toml [programs.{cluster}] missing `{program}`")
                    continue
                seen.add(prog_map[program])
            if len(seen) > 1:
                failures.append(
                    f"Anchor.toml declares `{program}` with differing IDs across clusters: {sorted(seen)}"
                )
            if program in declared and seen and declared[program] not in seen:
                failures.append(
                    f"declare_id!() in {DECLARE_ID_PATHS[program].relative_to(ROOT)} "
                    f"= {declared[program]!r} but Anchor.toml says {sorted(seen)!r}"
                )

    # (1b) SOLID-SEC-032 + ADR-0014: the hardcoded program-ID string
    # literals in solid-light/src/cpi_helpers.rs must each agree with
    # their corresponding entry in Anchor.toml.  If either drifts, the
    # on-chain owner-check (ADR-0010 for schema-registry; ADR-0014 for
    # issuer-registry) silently breaks.
    for const_name, anchor_key in (
        ("SCHEMA_REGISTRY_PROGRAM_ID", "schema_registry"),
        ("ISSUER_REGISTRY_PROGRAM_ID", "issuer_registry"),
    ):
        cpi_literal = read_cpi_helpers_literal(const_name)
        if cpi_literal is None:
            failures.append(
                f"missing {CPI_HELPERS_PATH.relative_to(ROOT)} -- "
                f"cannot validate {const_name} literal"
            )
            continue
        if cpi_literal == "":
            failures.append(
                f"{CPI_HELPERS_PATH.relative_to(ROOT)} does not define "
                f"`pub const {const_name}: &str = \"...\";` -- "
                "required by SOLID-SEC-032 / ADR-0014"
            )
            continue
        anchor_ids: set[str] = set()
        for _cluster, prog_map in anchor.items():
            if anchor_key in prog_map:
                anchor_ids.add(prog_map[anchor_key])
        if anchor_ids and cpi_literal not in anchor_ids:
            failures.append(
                f"{CPI_HELPERS_PATH.relative_to(ROOT)} "
                f"{const_name} = {cpi_literal!r} "
                f"but Anchor.toml says {sorted(anchor_ids)!r} -- "
                f"re-derive the base58 string and the matching "
                f"{anchor_key.upper()}_ID_BYTES array together "
                "(Rust tests in cpi_helpers.rs::id_bytes_tests gate the "
                "byte array)"
            )

    # (2) Every deployment manifest must agree with Anchor.toml for its cluster.
    for cluster, prog_map in deployments.items():
        anchor_for_cluster = anchor.get(cluster, {})
        for program, deployed_id in prog_map.items():
            expected = anchor_for_cluster.get(program)
            if expected is None:
                failures.append(
                    f"deployments/{cluster}.json has `{program}` = {deployed_id!r} "
                    f"but Anchor.toml [programs.{cluster}] has no entry"
                )
            elif expected != deployed_id:
                failures.append(
                    f"{cluster}: Anchor.toml `{program}` = {expected!r} "
                    f"≠ deployments/{cluster}.json `{program}` = {deployed_id!r}"
                )

    # (1c) SOLID-SEC-081 / NF-05: TypeScript pubkey literals.
    #
    # Walk the curated set of TS files and confirm every canonical
    # program-ID literal matches Anchor.toml; reject any non-allowlisted
    # TS file that hard-codes one of these IDs.  The drift surface here
    # is a typo in `ts-sdk/packages/core/src/index.ts::PROGRAM_PUBKEYS`
    # (or its siblings) silently breaking the on-chain owner-check at
    # issue / verify time -- the Rust gate above (1b) doesn't see TS.
    if anchor:
        # Collapse the per-cluster Anchor.toml table to a single canonical
        # ID per program (we already asserted at (1) that all clusters
        # agree).  Pick `localnet` as the canonical reading if present,
        # else any cluster's value.
        canonical = (
            anchor.get("localnet")
            or next(iter(anchor.values()), {})
        )
        canonical_ids: Dict[str, str] = {
            p: canonical[p] for p in PROGRAM_KEYS if p in canonical
        }
        owners_seen, ts_violations = scan_ts_files_for_pubkey_literals(canonical_ids)
        for v in ts_violations:
            failures.append(v)
        # Verify every allowlisted owner actually carries the IDs it's
        # meant to carry, and that the literals match canonical.  An
        # owner missing one of its declared programs is a structural
        # drift (someone deleted the constant); a literal that doesn't
        # match canonical is a typo.
        for owner_path, allowed_programs in TS_PROGRAM_ID_OWNERS.items():
            seen_for_file = owners_seen.get(owner_path, {})
            for program in allowed_programs:
                expected = canonical_ids.get(program)
                if expected is None:
                    continue
                actual = seen_for_file.get(program)
                if actual is None:
                    failures.append(
                        f"{owner_path} is allowlisted to carry the "
                        f"`{program}` program ID but no matching base58 "
                        f"literal was found.  Expected literal: "
                        f"{expected!r}.  Either restore the constant or "
                        f"narrow the allowlist entry."
                    )
                elif actual != expected:
                    failures.append(
                        f"{owner_path} has `{program}` literal {actual!r} "
                        f"but Anchor.toml says {expected!r}.  Re-derive "
                        f"the TS literal from Anchor.toml; SOLID-SEC-032 "
                        f"governs the Rust side, SOLID-SEC-081 governs "
                        f"this TS side."
                    )

    # (2b) Every non-local cluster declared in Anchor.toml must have a matching
    # deployment manifest.  Without this, deleting deployments/<cluster>.json
    # silently passes this gate even though CLAUDE.md's invariant is
    # "Anchor.toml, declare_id, and deployments all agree".  `localnet` is the
    # development stub and is not expected to have a published manifest.
    NON_LOCAL_CLUSTERS_REQUIRING_MANIFEST = {
        c for c in anchor.keys() if c != "localnet"
    }
    for cluster in NON_LOCAL_CLUSTERS_REQUIRING_MANIFEST:
        if cluster not in deployments:
            failures.append(
                f"Anchor.toml declares [programs.{cluster}] but "
                f"deployments/{cluster}.json is missing.  "
                "Either restore the manifest (via scripts/regen_devnet_manifest.py "
                f"or the cluster-specific equivalent) or drop the "
                f"[programs.{cluster}] section from Anchor.toml."
            )
        else:
            # Manifest exists; ensure every program from Anchor.toml appears.
            for program in PROGRAM_KEYS:
                if program not in deployments[cluster]:
                    failures.append(
                        f"deployments/{cluster}.json is missing `{program}`; "
                        f"Anchor.toml [programs.{cluster}] declares it."
                    )

    if failures:
        print("Program-ID consistency FAILED:", file=sys.stderr)
        for msg in failures:
            print(f"  - {msg}", file=sys.stderr)
        print(
            "\nFix procedure:\n"
            "  1. Decide the canonical IDs (usually the ones in Anchor.toml).\n"
            "  2. Close any stale deployments: `solana program close <ID> "
            "--lamports-recipient <authority>`.\n"
            "  3. Redeploy with the canonical IDs: `anchor deploy`.\n"
            "  4. Regenerate deployments/<cluster>.json to match.\n"
            "  5. Re-run scripts/store_vk.ts (VK PDA is keyed on program ID).",
            file=sys.stderr,
        )
        return 1

    print("Program IDs consistent across Anchor.toml, declare_id!, and deployments/.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
